### PR TITLE
Add example Ansible Playbook for Deadsnakes

### PR DESCRIPTION
**Pull request by cooperlees**
Took a guess at how you wanted documentation here - Just let me know what I did wrong.

### CODE REVIEW

**Comment by asottile** [comment]
hmmm github seems to be having trouble rendering rst -- maybe markdown would be easier / better ?

**Comment by cooperlees** [comment]
Is the goal to just have documentation here or is it to render to some other page? I'm a little lost there. So I did .rst cause the other documentation was. The rendering is probably just my lack of RST formatting skills.

If the docs are just living here I'll happily move to Markdown.

**Comment by asottile** [comment]
probably just to have it here, rtd seems pretty overkill for most of this (maybe if it gets larger / significantly more complicated?)

**Review by asottile — APPROVED** [review]

**Pull request merged**
